nodeLinker: pnpm

packageExtensions:
  '@pnpm/npm-resolver@*':
    dependencies:
      '@pnpm/logger': ^5.0.0
  '@koa/bodyparser@*':
    peerDependencies:
      'koa': '^2.14.2'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
