name: docs

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3

      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn
      - run: corepack enable
      - run: yarn set version 3.6.4

      - name: Validate API reference
        working-directory: ./docs
        run: |
          yarn
          yarn sync-snippets && yarn sync-api-reference
          yarn validate-api-reference

      - name: Build Docusaurus
        working-directory: ./docs
        run: yarn build

      - name: Prepare publish docs
        working-directory: ./
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          # Move Docusaurus static assets.
          mv docs/build ./output

          # Move @oas-typescript/swagger-ui static assets.
          mkdir -p ./output/oas-swagger-ui
          cp -r packages/oas-swagger-ui/dist/* output/oas-swagger-ui

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          # Publish only with the latest commit.
          # Source: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-force-orphan-force_orphan.
          force_orphan: true
