name: publish-swagger

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  publish-swagger:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
      - name: prepare publish
        working-directory: ./
        run: |
          mkdir -p ./output/oas-swagger-ui
          cp -r gh-pages/* output
          cp -r packages/oas-swagger-ui/dist/* output/oas-swagger-ui
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          # Publish only with the latest commit.
          # Source: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-force-orphan-force_orphan.
          force_orphan: true
