name: test-examples

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  koa:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3

      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn
      - run: corepack enable
      - run: yarn set version 3.6.4

      - run: npm install -g yalc
      - name: build the koa folder
        working-directory: ./packages/oas-typescript-koa
        run: |
          yarn 
          yarn build
          yalc publish

      - name: setup and run tests
        working-directory: ./examples/axios-koa
        run: |
          yarn
          yalc add @oas-typescript/koa
          yarn build
          yarn test
